### PR TITLE
Eng 143/upgrade heartbeat dns 6.3

### PR DESCRIPTION
**Pull request by tlloydaubry**
Advance our fork to the elastic/beats 6.3 branch. Add our basic DNS monitoring back into heartbeat. (very minimal changes)

### CODE REVIEW

**Review by supernomad — APPROVED** [review]
Way too much to review, lets try it out

**Comment by tlloydaubry** [comment]
Fixed golint errors in case we try to merge this.
How should we go about testing this out?
Did you still want to make changes to the dns monitoring logic?

**Comment by supernomad** [comment]
Nah lets get this landed and then to test it we will need to get elasticsearch rebuilt in prod0.

**Comment by tlloydaubry** [comment]
Is that something I can do? I'm happy to run some playbooks in prod0

**Comment by supernomad** [comment]
@tlloydaubry we should hop on a call there is a bunch of work to do to get this all working :)

**Comment by tlloydaubry** [comment]
Sick I'm all yours whenever you are free. We should also stop talking on github because i don't seem to get notifications when you reply or they're disappearing into the ether.

**Pull request merged**
